# Generated by Django 4.2.5 on 2023-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('links', models.URLField()),
                ('shorten_prefix', models.CharField(max_length=5, unique=True)),
                ('expiration', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
